spring.application.name=auth-service-api


server.port=9092

# database configuration
spring.datasource.url=jdbc:mysql://localhost:3307/cpd_hotel_auth?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=QW123Chathura
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

#============
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

#========= keycloak config
spring.security.oauth2.resourceserver.jwt.token-uri=http://3.111.106.206:8080/realms/cpd/protocol/openid-connect/token
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://3.111.106.206:8080/realms/cpd
public.key.string=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA25cNVxfknd24xkZ5km/TcI2gKGWNvbDUxdZlsyiCwVP28DKC9obRgsUK9o8qlWkHmBZuAxiE2/zABy11Twc57p9D31gSzyJB00BBrkVWy1yKItkZfElfjy/gLHjnqlNveB3YJUAqMJNGtpOURsIPZ1x48wlq+2knpxjz+e07N00drM9QHySWID+nrZUwWGJ4wxwanwgaOFdtlDFc5yIUX0FETzARwSKIEDm0/iiDE25UOZSloPsS40SH5i++nZrI5ao5N2PibWghSqs9hOOnqvlJNMBAjHd7CV0mX2+170j4mr8rO8kpBJ8iXtQz7j+FSF5O8WeKd1m7Ve/Nj9rfywIDAQAB
keycloak.config.realm=cpd
keycloak.config.server-url=http://3.111.106.206:8080/
keycloak.config.client-id=cpd-client
keycloak.config.grant-type=password
keycloak.config.name=chathuramalith456@gmail.com
keycloak.config.secret=ovnYXvVer3vnijN4fOu62868DgPpSVCs
keycloak.config.password=1234

#======== email configuration sendgrid
emailKey=${SENDGRID_API_KEY}
fromEmail=malithariyarathna6@gmail.com
replyEmail=malithariyarathna6@gmail.com

#======== aws s3 configuration
accessKey=${AWS_ACCESS_KEY}
secret=${AWS_SECRET_KEY}
bucketName=cpd-3-img
region=ap-southeast-1